def CheckoutCode() {
    echo "CheckoutCode, BRANCH_TYPE is ${BRANCH_TYPE}"
    sh "rm -rf ${WORKSPACE}/proton-rds-exporter/*"
    checkout(
        [
        $class : "GitSCM",
        branches: scm.branches,
        doGenerateSubmoduleConfigurations: false,
        extensions: [
            [
            $class: "RelativeTargetDirectory",
            relativeTargetDir: "./proton-rds-exporter"
            ]
        ],
        submoduleCfg: [],
        userRemoteConfigs: [
            [
            credentialsId: "bea73795-697a-49a6-a202-345c1aa588a0",
            url: "https://devops.aishu.cn/AISHUDevOps/ICT/_git/ProtonRDSExporter"
            ]
        ]
        ]
    )
}

def BuildImage(ARCH_TYPE) {
    echo "BuildImage, ARCH_TYPE is ${ARCH_TYPE}"
    dir("${WORKSPACE}/proton-rds-exporter/image") {
        def VERSION = sh(script: "cat ../VERSION", returnStdout: true).trim()

        def CURRENT_TAG = "${VERSION}-${BRANCH_NAME}.${BUILD_NUMBER}"
        def LATEST_TAG = "${VERSION}-${BRANCH_NAME}"
        if (BRANCH_TYPE == "release") {
            CURRENT_TAG = "${BRANCH_NAME}-${BUILD_NUMBER}"
            LATEST_TAG = "${BRANCH_NAME}"
        }

        def IMAGE_NAME = "acr.aishu.cn/proton/rds-exporter-${ARCH_TYPE}"
        def CURRENT_IMAGE = "${IMAGE_NAME}:${CURRENT_TAG}"
        def LATEST_IMAGE = "${IMAGE_NAME}:${LATEST_TAG}"

        sh "docker build -t ${CURRENT_IMAGE} ."
        sh "docker tag ${CURRENT_IMAGE} ${LATEST_IMAGE}"
        sh "docker push ${CURRENT_IMAGE}"
        sh "docker push ${LATEST_IMAGE}"
        sh "docker rmi ${CURRENT_IMAGE} ${LATEST_IMAGE}"
    }
}

def GetBranchType() {
    BRANCH_TYPE = "develop"
    if (BRANCH_NAME =~ "^ICT.*") {
        BRANCH_TYPE = "feature"
    } else if (BRANCH_NAME =~ "^develop.*") {
        BRANCH_TYPE = "develop"
    } else {
        BRANCH_TYPE = "release"
    }
    return BRANCH_TYPE
}

pipeline {
    agent none

    environment {
        BRANCH_TYPE = GetBranchType()
    }

    stages {
        stage("build image") {
            parallel {
                stage("amd64") {
                    agent {
                        node {
                            label "amd64"
                        }
                    }
                    stages {
                        stage("Build on amd64") {
                            steps {
                                CheckoutCode()

                                withDockerContainer(args: "-v ${WORKSPACE}/proton-rds-exporter:/go/src/proton-rds-exporter -e GO111MODULE=on", image: "acr.aishu.cn/ict/proton-rds-go-build-amd64:1.0.1") {
                                    //go tool cover -html=cover.out -o report/coverage.html
                                    sh "cd /go/src/proton-rds-exporter \
                                        && go build -o image/mysqld-exporter \
                                        && strip -g image/mysqld-exporter"
                                }

                                BuildImage("amd64")
                            }
                        }
                    }
                }

                stage("arm64") {
                    agent {
                        node {
                            label "arm64"
                        }
                    }
                    stages {
                        stage("Build on arm64") {
                            steps {
                                CheckoutCode()

                                withDockerContainer(args: "-v ${WORKSPACE}/proton-rds-exporter:/go/src/proton-rds-exporter -e GO111MODULE=on", image: "acr.aishu.cn/public/golang:1.16.2") {
                                    sh "cd /go/src/proton-rds-exporter \
                                        && go build -o image/mysqld-exporter \
                                        && strip -g image/mysqld-exporter"
                                }

                                BuildImage("arm64")
                            }
                        }
                    }
                }
            }
        }
        stage("build Manifest") {
            agent {
                node {
                    label "docker-builder"
                }
            }
            steps {
                CheckoutCode()

                dir("${WORKSPACE}/proton-rds-exporter") {
                    script {
                        def VERSION = sh(script: "cat VERSION", returnStdout: true).trim()
                        def CURRENT_TAG = "${VERSION}-${BRANCH_NAME}.${BUILD_NUMBER}"
                        def LATEST_TAG = "${VERSION}-${BRANCH_NAME}"
                        if (BRANCH_TYPE == "release") {
                            CURRENT_TAG = "${BRANCH_NAME}-${BUILD_NUMBER}"
                            LATEST_TAG = "${BRANCH_NAME}"
                        }

                        def IMAGE_NAME = "acr.aishu.cn/proton/rds-exporter"

                        sh "docker manifest create ${IMAGE_NAME}:${CURRENT_TAG} ${IMAGE_NAME}-amd64:${CURRENT_TAG} ${IMAGE_NAME}-arm64:${CURRENT_TAG}"
                        sh "docker manifest push -p ${IMAGE_NAME}:${CURRENT_TAG}"
                        sh "docker manifest create ${IMAGE_NAME}:${LATEST_TAG} ${IMAGE_NAME}-amd64:${LATEST_TAG} ${IMAGE_NAME}-arm64:${LATEST_TAG}"
                        sh "docker manifest push -p ${IMAGE_NAME}:${LATEST_TAG}"
                    }
                }
            }
        }
    }
}
