def CheckoutCode() {
    echo "CheckoutCode, BRANCH_TYPE is ${BRANCH_TYPE}"
    sh "rm -rf ${WORKSPACE}/proton-rds-mgmt-image/*"
    checkout(
        [
        $class : "GitSCM",
        branches: scm.branches,
        doGenerateSubmoduleConfigurations: false,
        extensions: [
            [
            $class: "RelativeTargetDirectory",
            relativeTargetDir: "./proton-rds-mgmt-image"
            ]
        ],
        submoduleCfg: [],
        userRemoteConfigs: [
            [
            credentialsId: "bea73795-697a-49a6-a202-345c1aa588a0",
            url: "https://devops.aishu.cn/AISHUDevOps/ICT/_git/proton-rds-mgmt-image"
            ]
        ]
        ]
    )
}

def BuildImage(ARCH_TYPE) {
    echo "BuildImage, ARCH_TYPE is ${ARCH_TYPE}"
    dir("${WORKSPACE}/proton-rds-mgmt-image") {
        def VERSION = sh(script: "cat VERSION", returnStdout: true).trim()

        def CURRENT_TAG = "${VERSION}-${BRANCH_NAME}.${BUILD_NUMBER}"
        def LATEST_TAG = "${VERSION}-${BRANCH_NAME}"
        if (BRANCH_TYPE == "release") {
            CURRENT_TAG = "${BRANCH_NAME}-${BUILD_NUMBER}"
            LATEST_TAG = "${BRANCH_NAME}"
        }

        def IMAGE_NAME = "acr.aishu.cn/proton/rds-mgmt-${ARCH_TYPE}"
        def CURRENT_IMAGE = "${IMAGE_NAME}:${CURRENT_TAG}"
        def LATEST_IMAGE = "${IMAGE_NAME}:${LATEST_TAG}"

        sh "docker build -t ${CURRENT_IMAGE} ."
        sh "docker tag ${CURRENT_IMAGE} ${LATEST_IMAGE}"
        sh "docker push ${CURRENT_IMAGE}"
        sh "docker push ${LATEST_IMAGE}"
        sh "docker rmi ${CURRENT_IMAGE} ${LATEST_IMAGE}"
    }
}

def GetBranchType() {
    BRANCH_TYPE = "develop"
    if (BRANCH_NAME =~ "^ICT.*") {
        BRANCH_TYPE = "feature"
    } else if (BRANCH_NAME =~ "^develop.*") {
        BRANCH_TYPE = "develop"
    } else {
        BRANCH_TYPE = "release"
    }
    return BRANCH_TYPE
}

pipeline {
    agent none

    environment {
        BRANCH_TYPE = GetBranchType()
    }

    stages {
        stage("build image") {
            parallel {
                stage("amd64") {
                    agent {
                        node {
                            label "amd64"
                        }
                    }
                    stages {
                        stage("Build on amd64") {
                            steps {
                                CheckoutCode()

                                sh "mkdir -p ${WORKSPACE}/proton-rds-mgmt-image/report"
                                withDockerContainer(args: "-v ${WORKSPACE}/proton-rds-mgmt-image:/go/src/proton-rds-mgmt -e GO111MODULE=off", image: "acr.aishu.cn/ict/proton-rds-go-build-amd64:1.0.1") {
                                    //go tool cover -html=cover.out -o report/coverage.html
                                    sh "cd /go/src/proton-rds-mgmt \
                                        && go generate ./... \
                                        && golangci-lint run ./... > report/golint.xml \
                                        && go test -gcflags=all=-l -v -coverprofile=cover.out ./... 2>&1 | go-junit-report > report/ut_result.xml \
                                        && gocov convert cover.out | gocov-xml > report/ut_coverage.xml \
                                        && go build -o bin/proton-rds-mgmt \
                                        && strip -g bin/proton-rds-mgmt"
                                }

                                BuildImage("amd64")
                            }
                        }
                        stage("Upload Report") {
                            steps {
                                dir("${WORKSPACE}/proton-rds-mgmt-image/report") {
                                    script {
                                        def check = scanForIssues tool: checkStyle(pattern: "golint.xml"), sourceDirectory: "${WORKSPACE}/proton-rds-mgmt-image/report"

                                        publishIssues issues: [check]

                                        cobertura(
                                            autoUpdateHealth: false,
                                            autoUpdateStability: false,
                                            coberturaReportFile: "ut_coverage.xml",
                                            conditionalCoverageTargets: "70, 80, 90",
                                            failUnhealthy: false,
                                            failUnstable: false,
                                            lineCoverageTargets: "50, 60, 70",
                                            maxNumberOfBuilds: 0,
                                            methodCoverageTargets: "50, 60, 70",
                                            onlyStable: false,
                                            sourceEncoding: "ASCII"
                                        )
                                    }
                                }
                            }
                        }
                        stage("Upload FTP&Metrix") {
                            when {
                                environment name: "BRANCH_NAME", value: "develop"
                            }
                            steps {
                                script {
                                    def job_name_parts = env.JOB_NAME.tokenize("/") as String[]
                                    MY_DIR_NAME = job_name_parts[0]
                                    MY_JOB_NAME = job_name_parts[1]

                                    dir("${WORKSPACE}/proton-rds-mgmt-image/report") {
                                        ftpPublisher alwaysPublishFromMaster: false,
                                        continueOnError: false,
                                        failOnError: false,
                                        publishers: [
                                            [
                                                configName: "FTP_ICT_REPORT",
                                                transfers: [
                                                    [
                                                        asciiMode: false,
                                                        cleanRemote: false,
                                                        excludes: "",
                                                        flatten: false,
                                                        makeEmptyDirs: false,
                                                        noDefaultExcludes: false,
                                                        patternSeparator: "[, ]+",
                                                        remoteDirectory: "/report/${MY_DIR_NAME}/${MY_JOB_NAME}/${new Date().format('yyyyMMdd-HHmmss')}-${BUILD_NUMBER}",
                                                        remoteDirectorySDF: false,
                                                        sourceFiles: "*"
                                                    ]
                                                ],
                                                usePromotionTimestamp: false,
                                                useWorkspaceInPromotion: false,
                                                verbose: false
                                            ]
                                        ]
                                    }

                                    build job: "M_JenkinsMetrix", parameters: [string(name: "subsystem", value: "Proton")], propagate: false, wait: false
                                }
                            }
                        }
                    }
                }

                stage("arm64") {
                    agent {
                        node {
                            label "arm64"
                        }
                    }
                    stages {
                        stage("Build on arm64") {
                            steps {
                                CheckoutCode()

                                withDockerContainer(args: "-v ${WORKSPACE}/proton-rds-mgmt-image:/go/src/proton-rds-mgmt -e GO111MODULE=off", image: "acr.aishu.cn/public/golang:1.16.2") {
                                    sh "cd /go/src/proton-rds-mgmt \
                                        && go build -o bin/proton-rds-mgmt \
                                        && strip -g bin/proton-rds-mgmt"
                                }

                                BuildImage("arm64")
                            }
                        }
                    }
                }
            }
        }
        stage("build Manifest") {
            agent {
                node {
                    label "docker-builder"
                }
            }
            steps {
                CheckoutCode()

                dir("${WORKSPACE}/proton-rds-mgmt-image") {
                    script {
                        def VERSION = sh(script: "cat VERSION", returnStdout: true).trim()
                        def CURRENT_TAG = "${VERSION}-${BRANCH_NAME}.${BUILD_NUMBER}"
                        def LATEST_TAG = "${VERSION}-${BRANCH_NAME}"
                        if (BRANCH_TYPE == "release") {
                            CURRENT_TAG = "${BRANCH_NAME}-${BUILD_NUMBER}"
                            LATEST_TAG = "${BRANCH_NAME}"
                        }

                        def IMAGE_NAME = "acr.aishu.cn/proton/rds-mgmt"

                        sh "docker manifest create ${IMAGE_NAME}:${CURRENT_TAG} ${IMAGE_NAME}-amd64:${CURRENT_TAG} ${IMAGE_NAME}-arm64:${CURRENT_TAG}"
                        sh "docker manifest push -p ${IMAGE_NAME}:${CURRENT_TAG}"
                        sh "docker manifest create ${IMAGE_NAME}:${LATEST_TAG} ${IMAGE_NAME}-amd64:${LATEST_TAG} ${IMAGE_NAME}-arm64:${LATEST_TAG}"
                        sh "docker manifest push -p ${IMAGE_NAME}:${LATEST_TAG}"
                    }
                }
            }
        }
    }
}
